name: at_base2e15
description: >
  binary-to-text encoding schemes that represent binary data in an unicode
  string format, each unicode character represent 15 bits of binary data.
version: 1.0.0
homepage: https://github.com/atsign-foundation/base2e15


environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.11
